-- Create the user registration request table
CREATE TABLE T_USER_REGISTRATION_REQUEST (
  URR_ID_C VARCHAR(36) NOT NULL,
  URR_USERNAME_C VARCHAR(50) NOT NULL,
  URR_PASSWORD_C VARCHAR(100) NOT NULL,
  URR_EMAIL_C VARCHAR(100) NOT NULL,
  URR_CREATEDATE_D DATETIME NOT NULL,
  URR_STATUS_C VARCHAR(20) NOT NULL,
  URR_PROCESSDATE_D DATETIME,
  URR_PROCESSEDBY_C VARCHAR(36),
  PRIMARY KEY (URR_ID_C)
);

-- Create indexes
CREATE INDEX IDX_URR_USERNAME ON T_USER_REGISTRATION_REQUEST(URR_USERNAME_C);
CREATE INDEX IDX_URR_STATUS ON T_USER_REGISTRATION_REQUEST(URR_STATUS_C);

-- Update database version
UPDATE T_CONFIG SET CFG_VALUE_C = '32' WHERE CFG_ID_C = 'DB_VERSION';